# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'decode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '4.0'
  pod 'SWXMLHash', '~> 3.0.0’
  pod 'Result', '~> 3.0.0'
  pod 'SwiftyJSON'

  # Pods for decode

end
